package local.redes;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.MulticastSocket;
import java.net.NetworkInterface;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

//@author Lucas Sandro
public class BatePapo extends javax.swing.JFrame {

    private MulticastSocket socketRecv = null;
    private MulticastSocket socketSend = null;
    private InetAddress endereco = null;
    private int porta = 50000;
    private String usuario = null;
    private ReceiverThread receiverThread = null;

    public BatePapo() {
        initComponents();
        TfEndereco.setText("224.1.1.20");
        TfPorta.setText(String.valueOf(porta));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        TfEndereco = new javax.swing.JTextField();
        TfPorta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtConectar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaTexto = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TfUsuario = new javax.swing.JTextField();
        BtEnviar = new javax.swing.JButton();
        TfTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHAT");
        setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Endereco");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Porta");

        BtConectar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BtConectar.setText("Conectar");
        BtConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConectarActionPerformed(evt);
            }
        });

        TaTexto.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        TaTexto.setColumns(20);
        TaTexto.setRows(5);
        TaTexto.setEnabled(false);
        jScrollPane1.setViewportView(TaTexto);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Usuário");

        BtEnviar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BtEnviar.setText("Enviar");
        BtEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TfTexto)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtConectar)
                    .addComponent(TfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtEnviar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void BtConectarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            usuario = TfUsuario.getText();
            if (usuario == null || usuario.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o nome de usuário antes de conectar.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            endereco = InetAddress.getByName("224.1.1.20");
            porta = 50000;
            TfEndereco.setText(endereco.getHostAddress());
            TfPorta.setText(String.valueOf(porta));

            socketRecv = new MulticastSocket(porta);
            try {
                NetworkInterface nif = NetworkInterface.getByInetAddress(InetAddress.getLocalHost());
                socketRecv.joinGroup(new InetSocketAddress(endereco, porta), nif);
            } catch (Exception ex) {
                try {
                    socketRecv.joinGroup(endereco);
                } catch (Exception ex2) {
                    // ignore
                }
            }

            socketSend = new MulticastSocket();
            try {
                NetworkInterface nif2 = NetworkInterface.getByInetAddress(InetAddress.getLocalHost());
                socketSend.joinGroup(new InetSocketAddress(endereco, porta), nif2);
            } catch (Exception ex) {
                try {
                    socketSend.joinGroup(endereco);
                } catch (Exception ex2) {
                    // ignore
                }
            }

            receiverThread = new ReceiverThread();
            receiverThread.start();

            BtConectar.setEnabled(false);
            TfUsuario.setEnabled(false);
            TfEndereco.setEnabled(false);
            TfPorta.setEnabled(false);

            TaTexto.append("Conectado em " + endereco.getHostAddress() + ":" + porta + "\n");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void BtEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (socketSend == null) {
                JOptionPane.showMessageDialog(this, "Você precisa conectar antes de enviar mensagens.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String texto = TfTexto.getText();
            if (texto == null || texto.trim().isEmpty()) {
                return;
            }

            String mensagem = usuario + " diz: " + texto;
            byte[] msg = mensagem.getBytes();

            DatagramPacket dgPacket = new DatagramPacket(msg, msg.length, endereco, porta);
            socketSend.send(dgPacket);

            if (texto.equalsIgnoreCase("sair") || texto.equalsIgnoreCase("Sair")) {
                System.exit(0);
            }

            TfTexto.setText("");

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao enviar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatePapo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatePapo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatePapo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatePapo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatePapo().setVisible(true);
            }
        });
    }


    private javax.swing.JButton BtConectar;
    private javax.swing.JButton BtEnviar;
    private javax.swing.JTextArea TaTexto;
    private javax.swing.JTextField TfEndereco;
    private javax.swing.JTextField TfPorta;
    private javax.swing.JTextField TfTexto;
    private javax.swing.JTextField TfUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;

    private class ReceiverThread extends Thread {
        @Override
        public void run() {
            try {
                byte[] buf = new byte[128];
                while (true) {
                    DatagramPacket packet = new DatagramPacket(buf, buf.length);
                    socketRecv.receive(packet);
                    final String mensagem = new String(packet.getData(), 0, packet.getLength());

                    if (usuario != null && !mensagem.contains(usuario) && !mensagem.toLowerCase().contains("sair")) {
                        SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                TaTexto.append(mensagem + "\n");
                            }
                        });
                    }

                    buf = new byte[128];
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
}
